'use client'
import { useState } from 'react'
import posthog from 'posthog-js'

// Where the "Sign up" buttons send visitors. Confirmed: your auth page is at /auth.
const SIGNUP_URL = '/auth'

const EXAMPLE_TOPICS = ['Python', 'Conversational Spanish', 'Music Theory', 'The French Revolution', 'Investing Basics', 'Chess Openings']

const TYPE_STYLES: Record<string, { c: string; bg: string }> = {
  lesson:     { c: '#7aacef', bg: 'rgba(122,172,239,0.12)' },
  flashcards: { c: '#b090f0', bg: 'rgba(176,144,240,0.12)' },
  exercise:   { c: '#6abf8a', bg: 'rgba(106,191,138,0.12)' },
  review:     { c: '#e8a55a', bg: 'rgba(232,165,90,0.12)' },
  practice:   { c: '#6abf8a', bg: 'rgba(106,191,138,0.12)' },
}

// Theme tokens with hard fallbacks, so the box looks right even outside the app's theme context.
const C = {
  bg2: 'var(--bg2, #111318)', bg3: 'var(--bg3, #1a1c24)', bg4: 'var(--bg4, #22252f)',
  text: 'var(--text, #e8e6df)', text2: 'var(--text2, #9a9790)', text3: 'var(--text3, #5a5856)',
  amber: 'var(--amber, #d4853a)',
  border: 'var(--border, #2a2d37)', border2: 'var(--border2, #343845)',
  serif: 'var(--serif, "Playfair Display", serif)', sans: 'var(--sans, "DM Sans", sans-serif)', mono: 'var(--mono, "JetBrains Mono", monospace)',
  amberBg: 'rgba(212,133,58,0.10)',
}

export default function DemoBox() {
  const [topic, setTopic] = useState('')
  const [generating, setGenerating] = useState(false)
  const [streamText, setStreamText] = useState('')
  const [curriculum, setCurriculum] = useState<any>(null)
  const [error, setError] = useState('')
  const [openWeeks, setOpenWeeks] = useState<Record<number, boolean>>({ 0: true })

  const generate = async (override?: string) => {
    const t = (override ?? topic).trim()
    if (!t) { setError('Tell me what you want to learn first.'); return }
    if (override) setTopic(override)
    setError(''); setGenerating(true); setStreamText(''); setCurriculum(null)
    try {
      const res = await fetch('/api/demo/curriculum', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t }),
      })
      if (!res.ok) {
        const e = await res.json().catch(() => ({} as any))
        throw new Error(e.error || 'Something went wrong — try again in a moment.')
      }
      const reader = res.body!.getReader()
      const decoder = new TextDecoder()
      let full = ''
      let streamError = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        for (const line of decoder.decode(value).split('\n')) {
          if (!line.startsWith('data: ')) continue
          const data = line.slice(6).trim()
          if (data === '[DONE]') break
          try {
            const p = JSON.parse(data)
            if (p.error) streamError = p.error
            else if (p.text) { full += p.text; setStreamText(full.slice(-280)) }
          } catch { /* partial line, ignore */ }
        }
      }
      if (streamError) throw new Error(streamError)
      const match = full.match(/\{[\s\S]*\}/)
      if (!match) throw new Error('Could not read the plan — give it another try.')
      setCurriculum(JSON.parse(match[0]))
      posthog.capture('curriculum-generated', { source: 'demo', topic: t })
      try { localStorage.setItem('lp-demo-claim', JSON.stringify({ topic: t, plan: JSON.parse(match[0]) })) } catch {}
      setOpenWeeks({ 0: true })
    } catch (e: any) {
      setError(e?.message || 'Something went wrong — try again.')
    } finally {
      setGenerating(false); setStreamText('')
    }
  }

  const card: React.CSSProperties = { background: C.bg2, border: `1px solid ${C.border}`, borderRadius: 16 }

  // ---- RESULT ----
  if (curriculum) {
    const weeks = curriculum.weeks || []
    const totalSessions = weeks.reduce((a: number, w: any) => a + (w.days?.length || 0), 0)
    return (
      <div style={{ maxWidth: 640, margin: '0 auto', fontFamily: C.sans }}>
        <div style={{ ...card, padding: '24px 26px', marginBottom: 14 }}>
          <div style={{ fontSize: 9, fontFamily: C.mono, color: C.amber, textTransform: 'uppercase', letterSpacing: '0.14em', marginBottom: 8 }}>Your sample plan · generated by Claude</div>
          <div style={{ fontFamily: C.serif, fontSize: 26, color: C.text, lineHeight: 1.2, marginBottom: 6 }}>{curriculum.title}</div>
          {curriculum.overview && <div style={{ fontSize: 13.5, color: C.text2, lineHeight: 1.65, marginBottom: 14 }}>{curriculum.overview}</div>}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {[`${curriculum.totalWeeks} weeks`, `${curriculum.daysPerWeek} days/week`, `${curriculum.sessionTime}/session`, `${totalSessions} sessions`].map((chip, i) => (
              <span key={i} style={{ fontSize: 10, fontFamily: C.mono, padding: '3px 9px', borderRadius: 4, border: `1px solid ${C.border2}`, background: C.bg3, color: C.text3 }}>{chip}</span>
            ))}
          </div>
        </div>

        <a href={SIGNUP_URL} style={{ display: 'block', textDecoration: 'none', marginBottom: 18 }}>
          <div style={{ background: C.amber, borderRadius: 12, padding: '14px 18px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
            <div style={{ color: '#0a0b0f' }}>
              <div style={{ fontSize: 14, fontWeight: 600 }}>Sign up free to start these lessons</div>
              <div style={{ fontSize: 11.5, opacity: 0.8 }}>Full lessons, flashcards, quizzes & an AI tutor — no card required.</div>
            </div>
            <div style={{ fontSize: 18, color: '#0a0b0f', flexShrink: 0 }}>→</div>
          </div>
        </a>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {weeks.map((wk: any, wi: number) => (
            <div key={wi} style={{ background: C.bg2, border: `1px solid ${wi === 0 ? 'rgba(212,133,58,0.4)' : C.border}`, borderRadius: 12, overflow: 'hidden' }}>
              <div onClick={() => setOpenWeeks(w => ({ ...w, [wi]: !w[wi] }))} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '13px 16px', cursor: 'pointer' }}>
                <div style={{ width: 32, height: 32, borderRadius: 8, background: wi === 0 ? C.amberBg : C.bg4, border: `1px solid ${wi === 0 ? 'rgba(212,133,58,0.4)' : C.border2}`, fontFamily: C.mono, fontSize: 11, color: wi === 0 ? C.amber : C.text3, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>W{wi + 1}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 13.5, fontWeight: 500, color: C.text }}>{wk.theme}</div>
                  <div style={{ fontSize: 10, fontFamily: C.mono, color: C.text3, marginTop: 2 }}>Week {wi + 1} · {(wk.days || []).length} sessions</div>
                </div>
                <div style={{ fontSize: 12, color: C.text3, transform: openWeeks[wi] ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }}>▾</div>
              </div>
              {openWeeks[wi] && (
                <div style={{ borderTop: `1px solid ${C.border}`, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 7 }}>
                  {(wk.days || []).map((d: any, di: number) => {
                    const ts = TYPE_STYLES[d.type] || TYPE_STYLES.lesson
                    return (
                      <div key={di} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '10px 12px', background: C.bg3, border: `1px solid ${C.border}`, borderRadius: 8 }}>
                        <div style={{ width: 22, height: 22, borderRadius: 5, background: C.bg4, border: `1px solid ${C.border2}`, fontFamily: C.mono, fontSize: 9, color: C.text3, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 }}>D{di + 1}</div>
                        <div style={{ flex: 1 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 3 }}>
                            <span style={{ fontSize: 8.5, fontFamily: C.mono, padding: '1px 6px', borderRadius: 3, textTransform: 'uppercase', letterSpacing: '0.06em', background: ts.bg, color: ts.c, border: `1px solid ${ts.c}44` }}>{d.type || 'lesson'}</span>
                            <span style={{ fontSize: 9, fontFamily: C.mono, color: C.text3, marginLeft: 'auto' }}>{d.duration}</span>
                          </div>
                          <div style={{ fontSize: 12.5, fontWeight: 500, color: C.text, marginBottom: 2 }}>{d.title}</div>
                          <div style={{ fontSize: 11.5, color: C.text2, lineHeight: 1.5 }}>{d.description}</div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: 10, marginTop: 18 }}>
          <a href={SIGNUP_URL} style={{ flex: 2, textDecoration: 'none' }}>
            <div style={{ textAlign: 'center', padding: 13, borderRadius: 10, background: C.amber, color: '#0a0b0f', fontSize: 13.5, fontWeight: 600 }}>Sign up free & start learning</div>
          </a>
          <button onClick={() => { setCurriculum(null); setTopic(''); setError('') }} style={{ flex: 1, padding: 13, borderRadius: 10, border: `1px solid ${C.border}`, background: C.bg2, color: C.text2, fontFamily: C.sans, fontSize: 13, cursor: 'pointer' }}>Try another</button>
        </div>
      </div>
    )
  }

  // ---- GENERATING ----
  if (generating) {
    return (
      <div style={{ maxWidth: 640, margin: '0 auto', fontFamily: C.sans }}>
        <div style={{ ...card, padding: '40px 28px', textAlign: 'center' }}>
          <div style={{ width: 38, height: 38, border: `2px solid ${C.border2}`, borderTopColor: C.amber, borderRadius: '50%', margin: '0 auto 20px', animation: 'lpspin 0.8s linear infinite' }} />
          <div style={{ fontFamily: C.serif, fontSize: 21, color: C.text, marginBottom: 6 }}>Claude is building your plan…</div>
          <div style={{ fontSize: 13, color: C.text2, marginBottom: streamText ? 20 : 0 }}>Designing a 2-week starter curriculum for "{topic}"</div>
          {streamText && (
            <div style={{ background: C.bg2, border: `1px solid ${C.border}`, borderRadius: 8, padding: '12px 14px', fontFamily: C.mono, fontSize: 10.5, color: C.text3, lineHeight: 1.6, maxHeight: 110, overflow: 'hidden', textAlign: 'left' }}>{streamText}</div>
          )}
        </div>
        <style>{`@keyframes lpspin { to { transform: rotate(360deg) } }`}</style>
      </div>
    )
  }

  // ---- INPUT ----
  return (
    <div style={{ maxWidth: 640, margin: '0 auto', fontFamily: C.sans }}>
      <div style={{ ...card, padding: '28px 26px' }}>
        <div style={{ fontFamily: C.serif, fontSize: 22, color: C.text, marginBottom: 6, lineHeight: 1.25 }}>See it in action — free, no signup</div>
        <div style={{ fontSize: 13, color: C.text2, marginBottom: 18 }}>Type anything you want to learn and watch Claude build a real curriculum in seconds.</div>
        <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
          <input
            value={topic}
            onChange={e => setTopic(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter') generate() }}
            placeholder="e.g. Python, conversational Spanish, the French Revolution…"
            maxLength={200}
            style={{ flex: 1, padding: '12px 14px', background: C.bg3, border: `1px solid ${C.border2}`, borderRadius: 9, color: C.text, fontFamily: C.sans, fontSize: 14, outline: 'none' }}
          />
          <button onClick={() => generate()} style={{ padding: '12px 20px', borderRadius: 9, border: 'none', background: C.amber, color: '#0a0b0f', fontFamily: C.sans, fontSize: 13.5, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0 }}>Build it →</button>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
          {EXAMPLE_TOPICS.map(t => (
            <button key={t} onClick={() => generate(t)} style={{ padding: '5px 12px', borderRadius: 14, fontSize: 11.5, border: `1px solid ${C.border}`, background: C.bg3, color: C.text3, cursor: 'pointer', fontFamily: C.mono }}>{t}</button>
          ))}
        </div>
        {error && <div style={{ marginTop: 14, padding: '9px 12px', borderRadius: 7, fontSize: 12, background: 'rgba(239,122,122,0.1)', border: '1px solid rgba(239,122,122,0.3)', color: '#ef7a7a' }}>{error}</div>}
      </div>
    </div>
  )
}
